use_frameworks!

target 'VEditorKit_Example' do
  pod 'VEditorKit', :path => '../'
  pod 'Texture', '2.7'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'VEditorKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest'
    pod 'RxBlocking'
  end
end
