use_frameworks!

target 'VEditorKit_Example' do
  pod 'VEditorKit', :path => '../'

  target 'VEditorKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
